### ISSUE TITLE
Failed to run executible on clean windows install

### ISSUE THREAD

**Issue by D4v1dW3bb** [mattpodraza/webview2#20]
Hi matt,

While everything should be embedded in one executable it should be possible to run the executable on an other computer.
I've just build your advanced example. Installed a fresh instance of windows on vmware player and moved the executable to that instance. 

When I run it i get:

```2021/06/15 02:28:31 Failed to create webview2: failed to initialize the window: failed to embed the browser: failed to call CreateCoreWebView2EnvironmentWithOptions: The system could not find the environment option that was entered.```

It looks like it's some how not embedded :(.

On the development machine it works.

Regards,

D4v1d

**Comment by mattpodraza** [comment]
Hey,

Sorry for not responding sooner, I didn't realise I had notifications turned off for this repo.

1. What version of Windows did you install on the VM?
2. Did you install the webview2 runtime? (https://github.com/mattpodraza/webview2#notice)
That's the one bit that can't be embedded in the resulting binary.

**Comment by D4v1dW3bb** [comment]
Thanks for your response. It is not clear that you also should install the runtime. I understand now that best way to go is to include the webview2 installer in your executable installer.

 

Met vriendelijke groet,

 

Didier M.J.C. Gehéniau

 

Van: Matt Podraza ***@***.***> 
Verzonden: maandag 21 juni 2021 17:46
Aan: mattpodraza/webview2 ***@***.***>
CC: D4v1dW3bb ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mattpodraza/webview2] Failed to run executible on clean windows install (#20)

 

Hey,

Sorry for not responding sooner, I didn't realise I had notifications turned off for this repo.

1.	What version of Windows did you install on the VM?
2.	Did you install the webview2 runtime? (https://github.com/mattpodraza/webview2#notice)
That's the one bit that can't be embedded in the resulting binary.

**Comment by mattpodraza** [comment]
I thought that putting the notice in README would be clear enough.
Do you have an idea on how to communicate that requirement in a clearer way? I'll gladly take a PR to update the README as well.

Regarding distribution of apps with webview2, see these docs from Microsoft, there are a few options: https://docs.microsoft.com/en-gb/microsoft-edge/webview2/concepts/distribution

Does that answer your questions?

**Comment by D4v1dW3bb** [comment]
It should, but even for me who tell users to read the full readme it’s not fail safe ☹. Maybe you should mention it after the first line like. “warning: you still need to install the webview2 runtime!”

 

Met vriendelijke groet,

 

Didier M.J.C. Gehéniau

 

Van: Matt Podraza ***@***.***> 
Verzonden: maandag 21 juni 2021 18:27
Aan: mattpodraza/webview2 ***@***.***>
CC: D4v1dW3bb ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mattpodraza/webview2] Failed to run executible on clean windows install (#20)

 

I thought that putting the notice in README would be clear enough.
Do you have an idea on how to communicate that requirement in a clearer way? I'll gladly take a PR to update the README as well.

Regarding distribution of apps with webview2, see these docs from Microsoft, there are a few options: https://docs.microsoft.com/en-gb/microsoft-edge/webview2/concepts/distribution

Does that answer your questions?

**Comment by mattpodraza** [comment]
I think that reading a short README is a reasonable expectation, especially for something that is definitely not production-ready, like this repo.

I think it'll be best to add a section on distributing apps with webview2, I'll do that later.

I'll go ahead and close this issue then, feel free to open it again if you encounter further issues with the runtime installed :)
