### ISSUE TITLE
question: this lib does not need compile c or c++ file ?

### ISSUE THREAD

**Issue by bung87** [mattpodraza/webview2#21]
I want make a binding in nim language, all I found repos wraps c++ file, that I need compile though c++ compiler and link to c program.I dont like the workflow, so I found this for another solution.

**Comment by mattpodraza** [comment]
This doesn't require compiling any C/C++, it's all pure Go (https://go.dev/).

I never heard of Go <-> Nim interoperability, and a quick search only hints at C++ <-> Nim interop in some way, but I've never used Nim myself so I'm not sure if that's what you were referring to.

I'm afraid this repo is not what you're looking for - even if it was it's experimental code that I no longer use myself and wouldn't include as a critical dependency of a project.

It might be a decent starting point if you dislike cgo and can live with the many caveats this comes with.

**Comment by bung87** [comment]
Thanks for your comment, I've starting porting it to nim , https://github.com/bung87/webview2 , havn't finish yet . code looks very similar.
